### ISSUE TITLE
Error: no module named lyc.data

### ISSUE THREAD

**Issue by dersuchendee** [liyucheng09/MetaphorFrame#1]
Running the script, I get this error: "no module named lyc.data". Why does it happen? I'm on Win10 if it's helpful.

**Comment by liyucheng09** [comment]
Thanks for your report. I will have a look.

**Comment by liyucheng09** [comment]
Let me know which command you're running.

**Comment by dersuchendee** [comment]
scripts\run.sh

**Comment by liyucheng09** [comment]
The issue is cause by the submodule `lyc` being set to provate. Now I have fixed this issue.

Please also check out the update in `readme.md` file. I added important instructions.

Let me know if you have further questions.

**Comment by dersuchendee** [comment]
Thank you! I just wanted to ask if I have a dataset to be labelled (with predicted metaphors), can I do it after I followed all the steps and if so how?

**Comment by liyucheng09** [comment]
I see. Current repo structure was designed to reproduce the results in the paper.
If you just want to annotate your data, I can add an `inference.py` later to simplify the overall procedure.

I can do it this weekend.

**Comment by dersuchendee** [comment]
It would be great thank you! I want to try to predict metaphors in my sentence data

**Comment by liyucheng09** [comment]
Hi, just to let you know. I didn't get to finish the updates last weekend. It's a bit tricky to add an `inference.py`. I think I can make it done within this month.

**Comment by liyucheng09** [comment]
I have finished adding a `inference.py`. Now you can perform metaphor detection directly without any training.

Please check out the updated `readme` to learn how to use our system on your own data.
