### ISSUE TITLE
no files in the 'checkpoints/mask_ff_combined/' directory

### ISSUE THREAD

**Issue by Caliiiiii** [liyucheng09/MetaphorFrame#2]
There are no files in the 'checkpoints/mask_ff_combined/' directory, running the script ff.sh only outputs various loss values.

**Comment by liyucheng09** [comment]
if you want me to help you diagnose your issue, provide as many details as possible. I cannot do anything given your message.

**Comment by liyucheng09** [comment]
Hi,

I have finished adding a `inference.py`. It should be very easy to use. Now you can perform metaphor detection directly without any training.

Please check out the updated readme to learn how to use our system on your own data.
