### ISSUE TITLE
Where can I find frame information in the predictions?

### ISSUE THREAD

**Issue by dersuchendee** [liyucheng09/MetaphorFrame#4]
I'd like predictions with 0 and 1 for metaphorical or not, but also the frames...is it something I'm doing wrong or is it like that?

**Comment by liyucheng09** [comment]
I see, I will update the software to allow frame detection from scratch. Please check the repo on next Monday.

**Comment by dersuchendee** [comment]
Thank you!! That's awesome.

**Comment by dersuchendee** [comment]
Any news on this? Thank you again so much

**Comment by liyucheng09** [comment]
check out latest updated `inference.py`. Now it does both metaphor and frame detection.
