### ISSUE TITLE
dill._dill.PY3 has no attribute PY3 on line 139 in inference.py

### ISSUE THREAD

**Issue by Niels-Engedal** [liyucheng09/MetaphorFrame#8]
Hello
I am a very new python programmer, but I found you paper and this model and it sounds awesome! I have tried setting up a virtual environment in python version 3.7.12, but I get an error when running it which is written in the top line. If you need more information please let me know (idk how to write an issue properly, so this is my try :))

Thanks in advance!

**Comment by saishivakalyan** [comment]
try again installing with the below version of dill.
dill==0.3.5.1.

I'm using Python 3.9.9

**Comment by Niels-Engedal** [comment]
Thank you that got past that error. I still seem to have a lot of errors, but I haven't started over with python 3.9.9, so I will do that before writing more. Thank you for the quick answer!
